
public class Euler2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

			By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
		*/
		int fib1=1;
		int fib2=2;
		int evenFibSum=2;
		int nextFib=0;
		while(true){
			nextFib=fib1+fib2;
			if(nextFib>=4000000)
				break;
			fib1=fib2;
			fib2=nextFib;
			System.out.println(nextFib);
			if(nextFib%2==0)
				evenFibSum=evenFibSum+nextFib;

		}
		System.out.println(evenFibSum);

		
		
	}

}
